- name: Include all variable files
  include_vars:
    dir: 'vars' #change directory if needed
    extensions:
        - yml

- name: Create Ethernet network for VLAN DMZ
  oneview_ethernet_network:
    config:'{{ config }}'
    state: present
    data:
      name: '{{ DMZ_VLAN }}'
      vlanId: '201'
      privateNetwork: false
      smartLink: false
      purpose: Management
      bandwidth:
          maximumBandwidth: 20000
          typicalBandwidth: 2500

- name: Create Ethernet network for VLAN Management
  oneview_ethernet_network:
    config: '{{ config }}'
    state: present
    data:
      name: '{{ MAN_VLAN }}'
      vlanId: '202'
      privateNetwork: false
      smartLink: false
      purpose: Management
      bandwidth:
          maximumBandwidth: 20000
          typicalBandwidth: 2500

- name: Create Ethernet network for VLAN Customer
  oneview_ethernet_network:
    config: '{{ config }}'
    state: present
    data:
      name: '{{ CUST_VLAN }}'
      vlanId: '203'
      privateNetwork: false
      smartLink: false
      purpose: Management
      bandwidth:
          maximumBandwidth: 20000
          typicalBandwidth: 2500

- name: Create Ethernet network for Management (Synergy)
  oneview_ethernet_network:
    config: '{{ config }}'
    state: present
    data:
      name:'{{ MAN_NET }}'
      vlanId: '1001'
      privateNetwork: false
      smartLink: false
      purpose: Management
      bandwidth:
          maximumBandwidth: 20000
          typicalBandwidth: 2500

- name: Create Ethernet network for Deployment (Synergy)
  oneview_ethernet_network:
    config: '{{ config }}'
    state: present
    data:
      name: '{{ DEPLOY_NET }}'
      vlanId: '1002'
      privateNetwork: false
      smartLink: false
      purpose: Management
      bandwidth:
          maximumBandwidth: 20000
          typicalBandwidth: 2500
#
- name: Gather facts about SAN A
  oneview_managed_san_facts:
    config: "{{ config }}"
    name: "{{ NET_SAN_A }}"
  delegate_to: localhost

- set_fact: SAN_A_Uri="{{ managed_sans[0].uri }}"
#
- name: Gather facts about SAN B
  oneview_managed_san_facts:
    config: "{{ config }}"
    name: "{{ NET_SAN_B }}"
  delegate_to: localhost

- set_fact: SAN_B_Uri="{{ managed_sans[0].uri }}"

- name: Create Fibre Channel network
  oneview_fc_network:
    config: '{{ config }}'
    state: present
    data:
      name: '{{ SAN_A }}'
      fabricType: 'FabricAttach'
      linkStabilityTime: '30'
      autoLoginRedistribution: true
      managedSanUri: '{{ SAN_A_Uri }}'

- name: Create Fibre Channel network
  oneview_fc_network:
    config: '{{ config }}'
    state: present
    data:
      name: '{{ SAN_B }}'
      fabricType: 'FabricAttach'
      linkStabilityTime: '30'
      autoLoginRedistribution: true
      managedSanUri: '{{ SAN_B_Uri }}'
