#
# gather Uri information and store as a local variable
#
- name: Gather facts about FC_r5
  oneview_storage_pool_facts:
    name: "{{ Vol_Stor_Pool5 }}"

- set_fact: Vol_Stor_Pool5_uri="{{ storage_pools[0].uri }}"

- name: Gather facts about Storage System
  oneview_storage_system_facts:
  delegate_to: localhost

- set_fact: Vol_Stor_Sys_Uri="{{ storage_systems[0].uri }}"
#
# Volume creation
#
- name: Create ESXi Shared Data Volume
  oneview_volume:
    state: present
    data:
      name: 'Tower Volume'
      description: 'Data Volume for ESXi'
      raidLevel: "RAID5"
      provisioningParameters:
          provisionType: 'Thin' #Thin or Full
          shareable: True
          requestedCapacity: "{{ c20Gb }}"
          storagePoolUri: "{{ Vol_Stor_Pool5_uri }}"
      storageSystemUri: "{{ Vol_Stor_Sys_Uri }}"
      snapshotPoolUri: "{{ Vol_Stor_Pool5_uri }}"
  delegate_to: localhost
