  vars:
    - config: "/opt/variables/oneview_config.json"  
  tasks:
    - name: Gather facts about all Connection Templates
      oneview_connection_template_facts:
        config: "{{ config }}"
      delegate_to: localhost
