- name: Gather facts about all Managed SANs
  oneview_managed_san_facts:
    config: "{{ config }}"
  delegate_to: localhost

- debug: var=managed_sans

- name: Gather facts about a Managed SAN by name
  oneview_managed_san_facts:
    config: "{{ config }}"
    name: "SAN_name"
  delegate_to: localhost

- debug: var=managed_sans
